spring:
  liquibase:
    change-log: classpath:db/config/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/filmstore?currentSchema=filmstore
    username: filmuser
    password: filmuser
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true